name: test-build

on:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  build:
      uses: ./.github/workflows/test-wf.yml
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Test job summary
        run: |
          echo "### Test! :rocket:" >> $GITHUB_STEP_SUMMARY
      - name: Test notice
        run: |
          echo "::notice title=Hello:: World!"
