name: test-build
run-name: Test Hello

on:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  build:
    uses: ./.github/workflows/test-wf.yml
      
  test:
    needs: [build]
    if: ${{ success() }}
    runs-on: ubuntu-22.04
    steps:
      - name: Test telegram
        run: |
          curl \
            -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_API_TOKEN }}/sendMessage \
            -H 'Content-Type: application/json' \
            -d '{"chat_id":"${{ secrets.TELEGRAM_CHAT_ID }}","text":"${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}", "parse_mode": "markdown"}' \
            --fail
