name: test-build
run-name: Test Hello

on:
  push:
    branches:
      - main
  pull_request:
    
jobs:
  build:
      uses: ./.github/workflows/test-wf.yml
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Test job summary
        run: |
          echo "### Test! :rocket:" >> $GITHUB_STEP_SUMMARY
      - name: Test notice
        run: |
          echo "::notice title=Hello:: World!"
      - name: Test telegram
        run: |
          curl \
            -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_API_TOKEN }}/sendMessage \
            -H 'Content-Type: application/json' \
            -d '{"chat_id":"{{ ${{ secrets.TELEGRAM_CHAT_ID }} }}","text":"Test", "parse_mode": "markdown"}'
